
name: 'dbt_ecommerce_analytics'
version: '1.0.0'

profile: 'dbt_ecommerce_analytics'

model-paths: ['models']
analysis-paths: ['analyses']
test-paths: ['tests']
seed-paths: ['seeds']
macro-paths: ['macros']
snapshot-paths: ['snapshots']

clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models


models:
  ecommerce_analytics:
    silver:
      +schema: silver_ecommerce
    gold:
      +schema: gold_ecommerce



# Configuring seeds


seeds:
  dbt_ecommerce_analytics:
    +quote_columns: false
    +materialized: seed

